require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ProprietariosController do

  # This should return the minimal set of attributes required to create a valid
  # Proprietario. As you add validations to Proprietario, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "nome" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ProprietariosController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all proprietarios as @proprietarios" do
      proprietario = Proprietario.create! valid_attributes
      get :index, {}, valid_session
      assigns(:proprietarios).should eq([proprietario])
    end
  end

  describe "GET show" do
    it "assigns the requested proprietario as @proprietario" do
      proprietario = Proprietario.create! valid_attributes
      get :show, {:id => proprietario.to_param}, valid_session
      assigns(:proprietario).should eq(proprietario)
    end
  end

  describe "GET new" do
    it "assigns a new proprietario as @proprietario" do
      get :new, {}, valid_session
      assigns(:proprietario).should be_a_new(Proprietario)
    end
  end

  describe "GET edit" do
    it "assigns the requested proprietario as @proprietario" do
      proprietario = Proprietario.create! valid_attributes
      get :edit, {:id => proprietario.to_param}, valid_session
      assigns(:proprietario).should eq(proprietario)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Proprietario" do
        expect {
          post :create, {:proprietario => valid_attributes}, valid_session
        }.to change(Proprietario, :count).by(1)
      end

      it "assigns a newly created proprietario as @proprietario" do
        post :create, {:proprietario => valid_attributes}, valid_session
        assigns(:proprietario).should be_a(Proprietario)
        assigns(:proprietario).should be_persisted
      end

      it "redirects to the created proprietario" do
        post :create, {:proprietario => valid_attributes}, valid_session
        response.should redirect_to(Proprietario.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved proprietario as @proprietario" do
        # Trigger the behavior that occurs when invalid params are submitted
        Proprietario.any_instance.stub(:save).and_return(false)
        post :create, {:proprietario => { "nome" => "invalid value" }}, valid_session
        assigns(:proprietario).should be_a_new(Proprietario)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Proprietario.any_instance.stub(:save).and_return(false)
        post :create, {:proprietario => { "nome" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested proprietario" do
        proprietario = Proprietario.create! valid_attributes
        # Assuming there are no other proprietarios in the database, this
        # specifies that the Proprietario created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Proprietario.any_instance.should_receive(:update).with({ "nome" => "MyString" })
        put :update, {:id => proprietario.to_param, :proprietario => { "nome" => "MyString" }}, valid_session
      end

      it "assigns the requested proprietario as @proprietario" do
        proprietario = Proprietario.create! valid_attributes
        put :update, {:id => proprietario.to_param, :proprietario => valid_attributes}, valid_session
        assigns(:proprietario).should eq(proprietario)
      end

      it "redirects to the proprietario" do
        proprietario = Proprietario.create! valid_attributes
        put :update, {:id => proprietario.to_param, :proprietario => valid_attributes}, valid_session
        response.should redirect_to(proprietario)
      end
    end

    describe "with invalid params" do
      it "assigns the proprietario as @proprietario" do
        proprietario = Proprietario.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Proprietario.any_instance.stub(:save).and_return(false)
        put :update, {:id => proprietario.to_param, :proprietario => { "nome" => "invalid value" }}, valid_session
        assigns(:proprietario).should eq(proprietario)
      end

      it "re-renders the 'edit' template" do
        proprietario = Proprietario.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Proprietario.any_instance.stub(:save).and_return(false)
        put :update, {:id => proprietario.to_param, :proprietario => { "nome" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested proprietario" do
      proprietario = Proprietario.create! valid_attributes
      expect {
        delete :destroy, {:id => proprietario.to_param}, valid_session
      }.to change(Proprietario, :count).by(-1)
    end

    it "redirects to the proprietarios list" do
      proprietario = Proprietario.create! valid_attributes
      delete :destroy, {:id => proprietario.to_param}, valid_session
      response.should redirect_to(proprietarios_url)
    end
  end

end
